name: Restaurant API workflow
on: push
jobs:
  test:
    environment: testing
    env:
      PORT: 8080
      HOST: localhost
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      NODE_ENV: development
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: 7
          run_install: false
      - name: Get PNPM Store Directory
        id: cache-dir
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
      - name: Echo STORE_PATH
        run: echo "store path is ${{ steps.cache-dir.outputs.STORE_PATH }}"
      - name: Cache Dependencies
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: ${{ steps.cache-dir.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Echo Cache Hit
        run: |
            echo "Cache Hit: ${{ steps.cache-deps.outputs }}"
      - name: Install dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run:  pnpm install
      # - name: Start Development Server
        # run: pnpm production && npx wait-on http://127.0.0.1:$PORT
      - name: Run Unit Tests
        run: pnpm utest
      - name: Run Integration Test
        run: pnpm itest
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        run: echo "Deploying....."