name: Restaurant API workflow
on: push
jobs:
  test:
    environment: testing
    env:
      PORT: 8080
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: 6.14.1
      - name: Get Store Directory
        id: cache-dir
        run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
      - name: Cache Dependencies
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: ${{ steps.cache-dir.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Echo Cache Hit
        run: |
            echo "Cache Hit: ${{ steps.cache-deps.outputs.cache-hit }}"
      - name: Install dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run:  pnpm i 
      - name: Start Development Server
        run: npm run start && npx wait-on http://127.0.0.1:$PORT
      - name: Run Unit Tests
        run: npm run utest
      - name: Run Integration Test
        run: npm run itest
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        run: echo "Deploying....."